services:
  backend:
    build: ./backend
    container_name: grocery_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data        # use folder, not grocery.db file
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped